Drop python 3.4 support.
Running tox against python 3.4 produces the following traceback::

  Error processing line 1 of /tmp/tox/py34/lib/python3.4/site-packages/distutils-precedence.pth:

    Traceback (most recent call last):
      File "/opt/bin/../python/3.4.10/lib/python3.4/site.py", line 167, in addpackage
        exec(line)
      File "<string>", line 1, in <module>
      File "/tmp/tox/py34/lib/python3.4/site-packages/_distutils_hack/__init__.py", line 194
        f'spec_for_{name}',
                         ^
    SyntaxError: invalid syntax

  Remainder of file ignored

This happens with tox 4.4.8, with tox 2.9.1 al testenvs run ok.
Anyway, I'm not using python 3.4 myself and I don't have time to
investigate the issue, so it's ok to drop support for this version.